export const CREATE_TASK = "CREATE_TASK";

export const ADD_CATEGORY = "ADD_CATEGORY";

export const SET_CATEGORY_ID_LIST = "SET_CATEGORY_ID_LIST";

export const CHANGE_CATEGORY_NAME = "CHANGE_CATEGORY_NAME";

export const DELETE_CATEGORY_BY_ID = "DELETE_CATEGORY_BY_ID";

export const TOGGLE_TASK_COMPLETION = "TOGGLE_TASK_COMPLETION";

export const REMOVE_TASK = "REMOVE_TASK";

export const SET_SEARCH_DATA = "SET_SEARCH_DATA";

export const CHANGE_TASK = "CHANGE_TASK";

export const DELETE_TASKS_OF_CATEGORY = "DELETE_TASKS_OF_CATEGORY";

