export const CREATE_TASK = 'CREATE_TASK';

export const ADD_CATEGORY = 'ADD_CATEGORY';

export const SET_CATEGORY_ID_LIST = 'SET_CATEGORY_ID_LIST';

export const CHANGE_CATEGORY_NAME = 'CHANGE_CATEGORY_NAME';

export const DELETE_CATEGORY_BY_ID = 'DELETE_CATEGORY_BY_ID';